### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by Git987886** [Fintecture/magento#9]
Hi, I'm getting this error during compilation on M 2.4.1

```
$ php bin/magento setup:di:compile
Compilation was started.
Interception cache generation... 6/9 [==================>---------]  66% 24 secs 490.0 MiB
Errors during compilation:
        Fintecture\Payment\Observer\Quote\SubmitObserver
                Missed required argument invoiceSender in parent::__construct call. File: /var/www/vhosts/website.com/httpdocs/vendor/fintecture/payment/Observer/Quote/SubmitObserver.php
Total Errors Count: 1

In Log.php line 92:
                            
  Error during compilation
```

**Comment by hugofintecture** [comment]
Thank you very much for the report! Fixed in the latest releases.

**Comment by hugofintecture** [comment]
We have reverted this change as this parameter has been deleted in Magento 2.4.3. You could stay on our V1.2.2 for now or update your Magento version to get our latest updates.

**Comment by Git987886** [comment]
Hi, 

This error is still showing on Magento 2.4.3 and 2.4.3p1 with your latest extension.

**Comment by Git987886** [comment]
Apologies, I forced the upgrade and the error has been resolved on 2.4.3 and 2.4.3p1
